#name of th WF
name: Code

on: 
  push:

jobs:
  code-checkouts:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Print the message
        run: echo "Code cloned"
