name : Deploy

on:
  workflow_call: #whenever we need the WF to be called from another WF

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Code clone
        uses: actions/checkout@v7

      - name: Deploy the code via nginx
        run: cp index.html /var/www/html

        
      - name: Build the code
        run: echo "Code built using AWS EC2 instance"
